@startuml

skinparam componentStyle uml2

package "'Especialidade' Aggregate" <<Rectangle>> {
	class Especialidade <<(A,#fffab8) Aggregate Root>> {
		String nome
		String status
		EspecialidadeId_Ref id
	}
	class EspecialidadeId_Ref <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
}
package "'TipoExame' Aggregate" <<Rectangle>> {
	class TipoExame <<(A,#fffab8) Aggregate Root>> {
		String codigo
		String descricao
		TipoExameId_Ref id
		Valor_Ref valorPadrao
		EspecialidadeId_Ref especialidade
	}
	class TipoExameId_Ref <<(V,DarkSeaGreen) Value Object>> {
		String codigo
	}
	class Valor_Ref <<(V,DarkSeaGreen) Value Object>> {
		Double quantia
	}
}
Especialidade --> EspecialidadeId_Ref : id
TipoExame --> TipoExameId_Ref : id
TipoExame --> Valor_Ref : valorPadrao
TipoExame --> EspecialidadeId_Ref : especialidade
legend left
  This bounded context implements the subdomain 'Referencia'.
end legend


@enduml
