@startuml

skinparam componentStyle uml2

component [Administracao]
component [Referencia]
component [Catalogo]
component [Atendimento]
component [Prontuario]
component [Financeiro]

[Atendimento]<-->[Administracao] : Shared Kernel

[Financeiro]<-->[Administracao] : Shared Kernel

[Prontuario]<-->[Administracao] : Shared Kernel

[Atendimento]<-->[Referencia] : Shared Kernel

[Prontuario]<-->[Catalogo] : Shared Kernel

[Administracao]<-->[Referencia] : Shared Kernel



@enduml
